Add version comparison functionality for package_version
trento-project/agent pull request #169
Opened 2023-01-13 12:01 UTC by rtorrero

[WIP]: Add support to compare versions on the agent using the package_version gatherer

2023-01-16 08:33 UTC, arbulu89 requested changes
I see some redundant call to get the version of the package.
PD: I wouldn't add not related changes to the PR

2023-01-16 08:33 UTC, arbulu89 commented on internal/factsengine/gatherers/packageversion.go
> +			gatheringError := PackageVersionCommandError.Wrap(packageName)
Do we need to wrap the error again? It is already wrapped and logged in `executeRpmVersionRetrieveCommand`.
It loos redundant

2023-01-16 08:33 UTC, arbulu89 commented on internal/factsengine/gatherers/packageversion.go
> +			installedVersion, err := executeRpmVersionRetrieveCommand(g.executor, packageName)
We don't need to run this again. You already have the version in `version`.
This way you can remove the next error checking as well

2023-01-16 08:33 UTC, arbulu89 commented on internal/factsengine/gatherers/packageversion.go
> +				gatheringError := PackageVersionCommandError.Wrap(packageName)
The same here. I don't think you need to wrap this

2023-01-16 08:33 UTC, arbulu89 commented on internal/factsengine/gatherers/packageversion.go
> +		fact = entities.NewFactGatheredWithRequest(factReq, &entities.FactValueString{Value: (version)})
What are these parenthesis in the `version` for?

2023-01-16 08:33 UTC, arbulu89 commented on internal/factsengine/gatherers/verifypassword.go
> +		var gatheringError *entities.FactGatheringError
Not a big fun of adding this off topic changes in this PR...
I wouldn't include them

2023-01-16 08:33 UTC, arbulu89 commented on internal/factsengine/gatherers/packageversion_test.go
> +	suite.mockExecutor.On("Exec", "/usr/bin/rpm", "-q", "--qf", "%{VERSION}", "corosync").Return(
Can we add some new test to check that errors during the comparison command work as expected? In fact, the test code doesn't check any scenario for failed commands

2023-01-16 14:13 UTC, nelsonkopliku approved these changes
Thanks!

2023-01-17 09:50 UTC, arbulu89 approved these changes
Thanks @rtorrero

2023-01-17 10:03 UTC, merged