Discovery context propagation
trento-project/agent pull request #360
Opened 2024-12-27 08:53 UTC by balanza

# Description

Please include a summary of the changes and the related issue, if it exists.
Also, include relevant motivation and context for this PR. List any dependencies that are required for this change.

Fixes # (issue)

## Did you add the right label?

Remember to add the right labels to this PR.

- [ ] **DONE**

## How was this tested?

Describe the tests that have been added/changed for this new behavior.

- [ ] **DONE**

## Did you update the documentation?

Remember to ask yourself if your PR requires changes to the following documentation:

- [Manual installation guide](https://github.com/trento-project/docs/blob/main/guides/manual-installation.md)
- [Trento Ansible guide](https://github.com/trento-project/ansible/blob/main/README.md)
- [Trento Agent guides](https://github.com/trento-project/agent/tree/main/docs)

Add a documentation PR or write that no changes are required for the documentation.

- [ ] **DONE**

2025-01-07 10:46 UTC, arbulu89 requested changes
Hey @balanza 
Looks mostly good.
Just two things. 
- I think we should use the context coming in `a.Start(ctx)` and pass it until reaching the gathering code
- We are passing this context because we are already using it in some gatherers. Could we use the passed context instead of creating a new one in the gatherer itself?
The gatherers that should be changed are: `ascsers_cluster`, `sapcontrol`, `systemd` and `systemd_v2` (just control+find hehe). I would keep the context usage in the `NewDefaultSystemDGathererV2` by now, as It would fail during initialization (we can pass it from above as well)

2025-01-07 10:46 UTC, arbulu89 commented on cmd/facts.go
> +	value, err := g.Gather(cmd.Context(), factRequest)
Maybe I bit out of context, but we don't have any proper canceling on this command.
Could we maybe add something like this (copied from the `start` command):
```
signals := make(chan os.Signal, 1)
signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM)

ctx, ctxCancel := context.WithCancel(context.Background())
// or
// ctx, ctxCancel := context.WithCancel(cmd.Context())

go func(ctx context.Context) {
	quit := <-signals
	log.Infof("Caught %s signal!", quit)

	log.Info("Stopping fact gathering...")
	ctxCancel()
}(ctx)

...

value, err := g.Gather(ctx, factRequest)
```

2025-01-07 10:46 UTC, arbulu89 commented on internal/factsengine/gatherers/_todo/crmmon_test.go
> +	factResults, err := p.Gather(context.Background(), actRequests)
typo? should be `factRequests`.
It is not executed, but better to have it right hehe

2025-01-07 10:46 UTC, arbulu89 commented on internal/factsengine/gathering.go
> +	g, groupCtx := errgroup.WithContext(context.Background())
We should get this context still from above.
The context we use everywhere should be the one coming in the start of the agent (`a.Start(ctx)`) in the `start.go` file.
Otherwise, we don't use the same context.
I know that we need to pass this context in many many functions, but I think it is worthy. Just put `ctx context.Context` in a bunch of functions.
What do you think?

2025-01-07 10:50 UTC, arbulu89 commented on cmd/facts.go
> +	value, err := g.Gather(cmd.Context(), factRequest)
I see this is coming in the next PR. We can discuss there.

2025-01-07 11:01 UTC, balanza commented on cmd/facts.go
> +	value, err := g.Gather(cmd.Context(), factRequest)
Indeed. 

I purposely avoid introducing behavior changes in this PR, as it's already fat.

2025-01-07 11:58 UTC, balanza commented on internal/factsengine/gathering.go
> +	g, groupCtx := errgroup.WithContext(context.Background())
I'm not sure the context to use is the one relative to the `Start` command. This context is scoped on each gathering request (coming from rabbitmq).

As I intended it, we want all routines in the same request to terminate on failure. If we use the root context, we will have the whole agent process to fail.

2025-01-07 12:16 UTC, arbulu89 commented on internal/factsengine/gathering.go
> +	g, groupCtx := errgroup.WithContext(context.Background())
> This context is scoped on each gathering request (coming from rabbitmq).

And it would continue this way, right? We would just be creating a new grouped context that can still be cancelled from above.

> If we use the root context, we will have the whole agent process to fail.
Is this true? 
I wouldn't expect the parent context being cancelled if some process in the group fails.
Maybe I'm wrong.

But what I would want is that if the parent context is cancelled (we stop trento agent), the gathering is cancelled and the execution stops, without leaving open traces or processes running.

If we create a new empty context, the stopping of the agent is not propagated to the gathering, and the gatherers that use contexts neither.

2025-01-07 13:26 UTC, balanza commented on internal/factsengine/gathering.go
> +	g, groupCtx := errgroup.WithContext(context.Background())
You're right, I didn't consider that scenario. I'll come up with a solution. Thanks!

2025-01-08 18:18 UTC, balanza commented
@arbulu89 some updates from the latest changes:
* now stopping the agent propagates the cancel signal to all the active gatherers (see https://github.com/trento-project/agent/pull/360/commits/3492b4d90fea66f47d27826130702c1ad3d9642f)
* same for the fact commands (see https://github.com/trento-project/agent/pull/360/commits/985b4ec605b4178b4e6fc70c447d7e08f93686f2)
* regardless of what I said in the comment before, one failing gatherer does not trigger cancellation on the others in its batch; this is because the actual logic is to collect both errors and results altogether.

2025-01-09 08:35 UTC, arbulu89 approved these changes
@balanza I wrote some "subjective" comments.
All good in any case.
Please don't forget using the `ctx` passed to the gatherers I mentioned in a previous comment before merging. Otherwise, all this is useless hehe

2025-01-09 08:35 UTC, arbulu89 commented on internal/factsengine/policy.go
> +type eventHandler func(name string, event []byte) error
question: why this new `makeEventHandler`?
was not enough to change the signature of of the `Listen` function in the `adapter.go` file to use the context?
I don't know, I find it more confusing than before.
Now, if we have other functions listening, the will need to copy this, which makes things more opaque in my opinion

2025-01-09 08:35 UTC, arbulu89 commented on internal/factsengine/gathering.go
> +	if err != nil {
nitpick: why do you remove the one liner? doesn't it look better?

2025-01-09 08:35 UTC, arbulu89 commented on internal/factsengine/gathering.go
> +			select {
question: here we are checking if the context is cancelled, right? At the end we are not waiting for it.
I think having this is equivalent:
```
newFacts, err := gatherer.Gather(groupCtx, factsRequest)
ctxErr := ctx.Err()
switch {
case ctxErr != nil:
    return ctxErr;
case err == nil:
    factsCh <- newFacts
...

// Or simply above the `switch`
if err := ctx.Err(); err != nil {
    return err
}
```
`ctx.Err` will return not nil if it is cancelled. Just to reuse the `switch`

2025-01-09 10:30 UTC, CDimonaco approved these changes
LGTM

I left some comments, nitpicks

2025-01-09 10:30 UTC, CDimonaco commented on cmd/facts.go
> +	if cancelled {
Good catch we can remove the second cleanup plugins, the defer gets called in any case

2025-01-09 10:30 UTC, CDimonaco commented on internal/factsengine/gatherers/rcp_plugin.go
> +func (g *PluggedGatherer) Gather(_ context.Context, factsRequests []entities.FactRequest) ([]entities.Fact, error) {
Nice 🤙🏻

2025-01-09 10:30 UTC, CDimonaco commented on internal/factsengine/gathering.go
> +			select {
Considering the select is blocking this could be another valid approach

2025-01-09 10:48 UTC, arbulu89 commented on cmd/facts.go
> +	if cancelled {
Okey, as long as we don't call the cleanup twice I'm fine

2025-01-09 10:58 UTC, balanza commented on internal/factsengine/gatherers/_todo/crmmon_test.go
> +	_, err := p.Gather(context.Background(), actRequests)
fixed in https://github.com/trento-project/agent/pull/360/commits/1d7198c4eedddd271b6b626afd65b23a03f5a745

2025-01-09 10:59 UTC, balanza commented on internal/factsengine/gathering.go
> +	if err != nil {
Unintentional, restored in https://github.com/trento-project/agent/pull/360/commits/c66e25b4bf909fb4aebf7830690e27b186833970

2025-01-09 11:01 UTC, balanza commented on internal/factsengine/gathering.go
> +			select {
Done in https://github.com/trento-project/agent/pull/360/commits/ab5a951135e076bc44c808f9b1d907c0e2a7d420

2025-01-09 11:08 UTC, balanza commented on internal/factsengine/policy.go
> +type eventHandler func(name string, event []byte) error
Because the listener in `FactsEngine.Listen` accepts a handling function with the signature `func(name string, event []byte) error`; and also, the context is coming from the scope not from the single event.

2025-01-09 11:24 UTC, balanza commented on cmd/facts.go
> +	if cancelled {
Looking twice: the `defer` won't happen after a `log.Fatal` so the cleanup won't happen twice. Not my favourite code design, though.

2025-01-09 11:25 UTC, arbulu89 commented on internal/factsengine/policy.go
> +type eventHandler func(name string, event []byte) error
Yes, of course, but you can change the signatures they way you prefer. That's not an issue
```
Listen(ctx context.Context, queue, exchange, routingKey string, handle func(ctx context.Context, contentType string, message []byte) error) error
```

2025-01-09 11:28 UTC, arbulu89 commented on cmd/facts.go
> +	if cancelled {
mmm, i don't get it. You are doing this in the main thread, and you have a `return` afterwards. Where is the `log.Fatal` happening when you cancel?

2025-01-09 11:31 UTC, balanza commented on cmd/facts.go
> +	if cancelled {
I'm referring to the `cleanupAndFatal` function, I removed the other occurrence in https://github.com/trento-project/agent/pull/360/commits/055f17694b0ea4be8d0830642af22f52fe343efb

2025-01-09 11:32 UTC, arbulu89 commented on cmd/facts.go
> +	if cancelled {
Yeah...
That was an ugly trick we implemented to always cleanup.
I'm not against changing it if we have a better alternative

2025-01-09 11:35 UTC, balanza commented on internal/factsengine/policy.go
> +type eventHandler func(name string, event []byte) error
Idk, because then the `ctx` should be passed by `RabbitMQAdapter.Listen` which is not aware of it

2025-01-09 12:43 UTC, arbulu89 commented on internal/factsengine/policy.go
> +type eventHandler func(name string, event []byte) error
I personally would pass it.
Up to you @balanza , I will respect the decision you take :slightly_smiling_face:

2025-01-10 13:40 UTC, merged